<?php

// $Id$

/**
 * @file
 *
 * Implements hooks and callbacks for this module.
 */
/**
 * Constants
 */
define("PERM_CONTENT_MODEL_VIEWER_VIEW_OBJECTS", 'View Objects & Datastreams');
define("PERM_CONTENT_MODEL_VIEWER_MODIFY_OBJECT_PROPERTIES", 'Modify Object Properties');
define("PERM_CONTENT_MODEL_VIEWER_PURGE_OBJECTS", 'Purge Objects');
define("PERM_CONTENT_MODEL_VIEWER_ADD_DATASTREAMS", 'Add Datastreams');
define("PERM_CONTENT_MODEL_VIEWER_PURGE_DATASTREAMS", 'Purge Datastreams');
define("PERM_CONTENT_MODEL_VIEWER_DOWNLOAD_DATASTREAMS", 'Download Datastreams');
define("PERM_CONTENT_MODEL_VIEWER_MODIFY_DATASTEAM_PROPERTIES", 'Modify Datastream Properties');
define("CONTENT_MODEL_VIEWER_SETTINGS_TABLE", 'content_model_viewer_models');
define("CONTENT_MODEL_VIEWER_DATASTREAM_DSID_RULES_TABLE", 'content_model_viewer_datastream_dsid_rules');
define("CONTENT_MODEL_VIEWER_DATASTREAM_MIMETYPE_RULES_TABLE", 'content_model_viewer_datastream_mimetype_rules');
define("CONTENT_MODEL_VIEWER_DEFAULT_SETTINGS_MODEL_ID", 1);

/**
 * Implements Menu Hook. Registers Menus.
 */
function content_model_viewer_menu() {
  $items['viewer/%'] = array(
    'title' => t('Content Model Viewer'),
    'description' => t('Allows users to view Fedora Objects.'),
    'page callback' => 'content_model_viewer',
    'page arguments' => array(1),
    'access arguments' => array(PERM_CONTENT_MODEL_VIEWER_VIEW_OBJECTS),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['viewer/%/members'] = array(
    'page callback' => 'content_model_viewer_members',
    'page arguments' => array(1),
    'access arguments' => array(PERM_CONTENT_MODEL_VIEWER_VIEW_OBJECTS),
    'type' => MENU_CALLBACK,
  );
  $items['viewer/%/properties'] = array(
    'page callback' => 'content_model_viewer_properties',
    'page arguments' => array(1),
    'access arguments' => array(PERM_CONTENT_MODEL_VIEWER_MODIFY_OBJECT_PROPERTIES),
    'type' => MENU_CALLBACK,
  );
  $items['viewer/%/datastreams'] = array(
    'page callback' => 'content_model_viewer_datastreams',
    'page arguments' => array(1),
    'access arguments' => array(PERM_CONTENT_MODEL_VIEWER_VIEW_OBJECTS),
    'type' => MENU_CALLBACK,
  );
  $items['viewer/%/overview'] = array(
    'page callback' => 'content_model_viewer_overview',
    'page arguments' => array(1),
    'access arguments' => array(PERM_CONTENT_MODEL_VIEWER_VIEW_OBJECTS),
    'type' => MENU_CALLBACK,
  );
  $items['viewer/%/purge'] = array(
    'page callback' => 'content_model_viewer_purge_object',
    'page arguments' => array(1),
    'access arguments' => array(PERM_CONTENT_MODEL_VIEWER_PURGE_OBJECTS),
    'type' => MENU_CALLBACK,
  );
  $items['viewer/%/add'] = array(
    'page callback' => 'content_model_viewer_add_datastream',
    'page arguments' => array(1),
    'access arguments' => array(PERM_CONTENT_MODEL_VIEWER_ADD_DATASTREAMS),
    'type' => MENU_CALLBACK,
  );
  $items['viewer/%/%/purge'] = array(
    'page callback' => 'content_model_viewer_purge_datastream',
    'page arguments' => array(1, 2),
    'access arguments' => array(PERM_CONTENT_MODEL_VIEWER_PURGE_DATASTREAMS),
    'type' => MENU_CALLBACK,
  );
  $items['viewer/%/%/download'] = array(
    'page callback' => 'content_model_viewer_download_datastream',
    'page arguments' => array(1, 2),
    'access arguments' => array(PERM_CONTENT_MODEL_VIEWER_DOWNLOAD_DATASTREAMS),
    'type' => MENU_CALLBACK,
  );
  $items['viewer/%/%/view'] = array(
    'page callback' => 'content_model_viewer_view_datastream',
    'page arguments' => array(1, 2),
    'access arguments' => array(PERM_CONTENT_MODEL_VIEWER_VIEW_OBJECTS),
    'type' => MENU_CALLBACK,
  );
  $items['viewer/%/%/properties'] = array(
    'page callback' => '',
    'page arguments' => array(1, 2),
    'access arguments' => array(PERM_CONTENT_MODEL_VIEWER_MODIFY_DATASTEAM_PROPERTIES),
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/content_model_viewer'] = array(
    'title' => t('Content Model Viewer Settings'),
    'description' => t('Settings for the Contet Model Viewer.'),
    'page callback' => 'theme',
    'page arguments' => array('content_model_viewer_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'content_model_viewer.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/settings/content_model_viewer/%/edit'] = array(
    'title' => t('Content Model Viewer Settings'),
    'description' => t('Settings for the Contet Model Viewer.'),
    'file' => 'content_model_viewer.admin.inc',
    'page callback' => 'theme',
    'page arguments' => array('content_model_viewer_custom_settings', 3),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/content_model_viewer/form/autocomplete/models'] = array(
    'page callback' => 'content_model_viewer_autocomplete_models',
    'access arguments' => array('administer site configuration'),
    'file' => 'content_model_viewer.admin.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_perm. Register permissions.
 *
 * @return array
 */
function content_model_viewer_perm() {
  return array(
    PERM_CONTENT_MODEL_VIEWER_VIEW_OBJECTS,
    PERM_CONTENT_MODEL_VIEWER_VIEW_OBJECTS,
    PERM_CONTENT_MODEL_VIEWER_MODIFY_OBJECT_PROPERTIES,
    PERM_CONTENT_MODEL_VIEWER_PURGE_OBJECTS,
    PERM_CONTENT_MODEL_VIEWER_ADD_DATASTREAMS,
    PERM_CONTENT_MODEL_VIEWER_PURGE_DATASTREAMS,
    PERM_CONTENT_MODEL_VIEWER_DOWNLOAD_DATASTREAMS,
    PERM_CONTENT_MODEL_VIEWER_MODIFY_DATASTEAM_PROPERTIES
  );
}

/**
 * Implements Hook Theme. Registers themes.
 *
 * @return array
 */
function content_model_viewer_theme() {
  return array(
    'content_model_viewer' => array(
      'arguments' => array('pid' => NULL),
      'template' => 'Viewer',
    ),
    'content_model_viewer_settings' => array(
      'template' => 'templates/Settings',
    ),
    'content_model_viewer_custom_settings' => array(
      'arguments' => array('pid' => NULL),
      'template' => 'templates/CustomSettings',
    ),
    'default_content_model_viewer' => array(
      'arguments' => array('pid' => NULL),
      'template' => 'models/Default',
    ),
    'field_book_content_model_viewer' => array(
      'arguments' => array('pid' => NULL),
      'template' => 'models/Default',
    ),
    'content_model_viewer_form_table' => array(
      'arguments' => array('element' => NULL)
    )
  );
}

/**
 * Loads all the installed module classes.
 */
function content_model_viewer_include_content_models() {
  $include_path = drupal_get_path('module', 'content_model_viewer') . "/models";
  $dir = opendir($include_path);
  if ($dir !== false) {
    while (($file = readdir($dir)) !== false) {
      if (preg_match('/\.inc$/', $file)) {
        require_once "$include_path/$file";
      }
    }
  }
  closedir($dir);
}

/**
 * Get the list of installed ContentModelViewer classes.
 */
function content_model_viewer_get_models() {
  $models = array();
  $classes = get_declared_classes();
  foreach ($classes as $class) {
    if ($class instanceof ContentModelViewer) {
      $models[] = $class;
    }
  }
  return $models;
}

/**
 * Loads all the installed viewer classes.
 */
function content_model_viewer_include_viewers() {
  $include_path = drupal_get_path('module', 'content_model_viewer') . "/viewers";
  $dir = opendir($include_path);
  if ($dir !== false) {
    while (($file = readdir($dir)) !== false) {
      if (preg_match('/\.inc$/', $file)) {
        require_once "$include_path/$file";
      }
    }
  }
  closedir($dir);
}

/**
 * Hook for register_content_models_for_viewer
 * 
 * @return array
 */
function content_model_viewer_register_content_models_for_viewer() {
  $models = array();
  $models['si:fieldbooks'] = array(
    'type' => 'inc',
    'module' => 'content_model_viewer',
    'file' => 'FieldBooks',
    'class' => 'FieldBookModelViewer'
  );
  return $models;
}

/**
 * Gets an instance of a content model viewer.
 * 
 * @param string $pid
 * 
 * @return object
 *   An instance of the Content Model Viewer if found. Otherwise it returns
 *   the default content model viewer.
 */
function content_model_viewer_get_registered_content_model_viewer($pid) {
  $model_pid = content_model_viewer_get_content_model_pid($pid);
  $models = module_invoke_all('register_content_models_for_viewer');
  foreach ($models as $key => $model) {
    if ($key == $model_pid) {
      module_load_include($model['type'], $model['module'], $model['file']);
      $class = $model['class'];
      return new $class($pid);
    }
  }
  module_load_include('inc', 'content_model_viewer', 'models/Default');
  return new DefaultModelViewer($pid);
}

/**
 * Get the pid of this objects content model.
 * 
 * @param string $pid
 * 
 * @return string
 */
function content_model_viewer_get_content_model_pid($pid) {
  module_load_include('inc', 'fedora_repository', 'ContentModel');
  $content_model = ContentModel::loadFromObject($pid);
  return $content_model->pid;
}

/**
 * Gets the Supported Viewers.
 * 
 * @staticvar array $cache
 * @return array
 */
function content_model_viewer_get_supported_viewers() {
  static $cache;
  if (!isset($cache)) {
    $cache = array();
    foreach (module_implements('elements') as $module) {
      $elements = module_invoke($module, 'elements');
      if (isset($elements) && is_array($elements)) {
        $cache = array_merge_recursive($cache, $elements);
      }
    }
  }
  return $cache;
}

/**
 * Sets up variables for the template.
 * 
 * @param array $variables
 */
function template_preprocess_content_model_viewer(array &$variables) {
  global $base_url;
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $pid = $variables['pid'];
  $item = new Fedora_Item($pid);
  $variables['label'] = $item->objectProfile->objLabel;
  $variables['base_url'] = $base_url;
  $variables['dsid'] = 'SWF';
  $variables['view_function'] = 'loadFlexPlayer';
  $variables['paths'] = array(
    'object' => array(
      'overview' => "viewer/$pid/overview",
      'properties' => "viewer/$pid/properties",
      'datastreams' => "viewer/$pid/datastreams",
      'members' => "viewer/$pid/members",
      'purge' => "viewer/$pid/purge"
    ),
    'datastream' => array(
      'add' => "viewer/$pid/add",
      'purge' => "viewer/$pid/dsid/purge",
      'properties' => "viewer/$pid/dsid/properties",
      'download' => "viewer/$pid/dsid/download",
      'view' => "viewer/$pid/dsid/view"
    )
  );
}

/**
 * Renders the Viewer for a given pid if possible.
 *
 * @param string $pid
 */
function content_model_viewer($pid) {
  global $base_url;
  $path = drupal_get_path('module', 'content_model_viewer');
  /* Load ExtJS */
  $ext_path = $path . '/lib/ext';
  drupal_add_js($ext_path . '/ext-all-dev.js');
  drupal_add_css($path . '/css/Clear.css');
  drupal_add_css($ext_path . '/resources/css/ext-all-gray.css', 'theme', 'all');
  /* Load Panels/Widgets */
  $js_path = $path . '/js';
  drupal_add_js($js_path . '/IncludeFirst.js');
  drupal_add_js($js_path . '/SortButton.js');
  drupal_add_js($js_path . '/OverviewPanel.js');
  drupal_add_js($js_path . '/ViewerPanel.js');
  drupal_add_js($js_path . '/ManagePanel.js');
  if (content_model_viewer_object_has_members($pid)) {
    drupal_add_js($js_path . '/CollectionPanel.js');
  }
  drupal_add_js($js_path . '/ContentModelViewer.js');
  drupal_add_css($path . '/css/ContentModelViewer.css');
  /* Load Viewers */
  module_load_include('inc', 'content_model_viewer', 'viewers/AbstractViewer');
  AbstractViewer::LoadRequiredResourcesForAllViewers();
  return theme('content_model_viewer', $pid);
}

/**
 * Returns the HTML for overview panel in the viewer.
 * 
 * @param string $pid 
 * 
 * @return string
 */
function content_model_viewer_overview($pid) {
  $viewer = content_model_viewer_get_registered_content_model_viewer($pid);
  try {
    echo $viewer->getOverview();
  } catch (Exception $e) {
    drupal_set_message($e->getMessage());
  }
  exit();
}

/**
 * Gets the members of this collection.
 * 
 * @param string $pid 
 */
function content_model_viewer_members($pid) {
  module_load_include('inc', 'content_model_viewer', 'Collection');
  $collection = new Collection($pid);
  list($data, $total) = $collection->getMembers();
  echo json_encode(array('success' => TRUE, 'data' => $data, 'total' => $total));
  exit();
  /**
   * 'link' => $base_url . '/viewer/' . 'coccc:1675',
   * 'label' => 'Some Colorado College Object',
   * 'description' => 'The Colorado College Nugget, formerly the Pikes Peak Nugget from 1900-1941, was issued until 2006-2007. The 1969-1970 Nugget was issued as loose photosheets contained in a box and named the The Colorado College Nugget, formerly the Pikes Peak Nugget from 1900-1941, was issued until 2006-2007. The 1969-1970 Nugget was issued as loose photosheets contained in a box and named the The Colorado College Nugget, formerly the Pikes Peak Nugget from 1900-1941, was issued until 2006-2007. The 1969-1970 Nugget was issued as loose photosheets contained in a box and named the',
   * 'owner' => 'fedoraAdmin',
   * 'created' => '2011-06-17T15:15:57.214Z',
   * 'modified' => '2011-07-15T19:08:16.008Z',
   * 'tn' => '/' . $module_path . '/images/collection.png',
   */
}

/**
 * 
 * 
 * @param string $pid 
 */
function content_model_viewer_datastreams($pid) {
  $filter = isset($_GET['filter']) ? $_GET['filter'] : false;
  //$viewer = content_model_viewer_get_registered_content_model_viewer($pid);
  //list($data, $total) = $viewer->getDatastreams($filter);

  echo json_encode(array('success' => TRUE, 'data' => $data, 'total' => $total));
  exit();
}

/**
 * Get/Set a datastreams properties.
 * 
 * @param string $pid
 * @param string $dsid 
 */
function content_model_viewer_datastream($pid, $dsid) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $item = new Fedora_Item($pid);
  if (isset($item->datastreams[$dsid])) {
    $datastream = $item->datastreams[$dsid];
    switch ($_SERVER['REQUEST_METHOD']) {
      case 'PUT':
        if ($_SERVER['CONTENT_LENGTH'] > 0) {
          $stdin = fopen("php://input", "r");
          $json = fread($stdin, $_SERVER['CONTENT_LENGTH']);
          $data = json_decode($json);
          // @todo Update the datastreams properties ...
          $data->created = "NOW";
          echo json_encode(array('success' => TRUE, 'msg' => "Successfully modified $dsid's properties", 'data' => $data));
          exit();
        }
        break;
    }
  }
  echo json_encode(array('success' => FALSE, 'msg' => "Datastream $dsid does not exist."));
  exit();
}

/**
 * Gets/sets the properties of the object identified by $pid.
 *
 * @param string $pid
 * 
 * @return string
 */
function content_model_viewer_properties($pid) {
  module_load_include('inc', 'content_model_viewer', 'ObjectProperties');
  switch ($_SERVER['REQUEST_METHOD']) {
    case 'GET':
      $object_properties = new ObjectProperties($pid);
      $properties = $object_properties->getProperties();
      echo json_encode(array('success' => TRUE, 'data' => array($properties)));
      exit();
    case 'POST':
      $label = $_POST['label'];
      $owner = $_POST['owner'];
      $state = $_POST['state'];
      $object_properties = new ObjectProperties($pid);
      $success = $object_properties->setProperties($label, $owner, $state);
      $message = $success ? t('Successfuly modified object properties') : t('Failed to modify object properties');
      $properties = $object_properties->getProperties();
      echo json_encode(array('success' => TRUE, 'msg' => $message, 'data' => $properties));
      exit();
  }
}

/**
 * Purges the object identified by $pid.
 *
 * The user will be redirected to the sites home page.
 *
 * @param string $pid 
 *
 * @return string
 */
function content_model_viewer_purge_object($pid) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $item = new Fedora_Item($pid);
  $success = $item->purge();
  $message = $success ? t('Successfuly deleted object') : t('Failed to delete object');
  echo json_encode(array('success' => $success, 'msg' => $message));
  exit();
}

/**
 * Adds a datastream to the object identified by $pid.*
 *
 * @param string $pid 
 *
 * @return string
 */
function content_model_viewer_add_datastream($pid) {
  $values = $_POST;
  $dsid = $_POST['dsid'];
  $label = $_POST['label'];
  $control = $_POST['control']; // Manage
  $file = array_shift($_FILES);
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $success = false;
  if ($file['error'] == UPLOAD_ERR_OK) {
    try {
      $item = new Fedora_Item($pid);
      if (empty($item->datastreams[$dsid])) {
        $success = $item->add_datastream_from_file($file['tmp_name'], $dsid, $label, NULL, $control);
      }
    } catch (Exception $e) {
      // log some error...
    }
  }
  $message = $success ? t('Successfully added datastream.') : t('Failed to add datastream.');
  echo json_encode(array('success' => $success, 'msg' => $message));
  exit();
}

/**
 * Purges the given datastream ($dsid) from the object identified by $pid.
 *
 * @param string $pid 
 * @param string $dsid
 *
 * @return string
 */
function content_model_viewer_purge_datastream($pid, $dsid) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $item = new Fedora_Item($pid);
  $success = $item->purge_datastream($dsid);
  $message = $success ? t('Successfully purged datastream.') : t('Failed to purge datastream.');
  echo json_encode(array('success' => $success, 'msg' => $message));
  exit();
}

/**
 * Downloads the given datastream ($dsid) from the object identified by $pid.
 *
 * @param string $pid 
 * @param string $dsid
 *
 * @return string
 */
function content_model_viewer_download_datastream($pid, $dsid) {
  module_load_include('inc', 'content_model_viewer', 'Download');
  download_datastream($pid, $dsid);
}

/**
 * Renders the viewer for the given datastream ($dsid) from the object identified by $pid.
 *
 * @param string $pid 
 * @param string $dsid
 *
 * @return string
 */
function content_model_viewer_view_datastream($pid, $dsid) {
  content_model_viewer_include_viewers();
  // @todo get the viewer for the datastream
  $viewer_exists = false;
  if (!$viewer_exists) {
    $viewer = new FlexPaperViewer();
    echo $viewer->render($pid, $dsid);
    exit();
  }
  exit();
}

/**
 * Gets/set the properties of the given datastream ($dsid) from the object identified by $pid.
 *
 * @param string $pid 
 * @param string $dsid
 *
 * @return string
 */
function content_model_viewer_datastream_properties($pid, $dsid) {
  module_load_include('inc', 'content_model_viewer', 'DatastreamProperties');
  if (empty($_POST)) {
    // @todo detect if the datastream doesn't exist and respond accordingly
    $datastream_properties = new DatastreamProperties($pid);
    list($properties, $total) = $datastream_properties->getProperties();
    return json_encode(array('success' => TRUE, 'data' => $properties, 'total' => $total));
  }
  else {
    $datastream_properties = new DatastreamProperties($pid);
    $success = $datastream_properties->setProperties(/* Determine the fields we want to pass here */);
    $message = $success ? t('Successfuly modified datastream properties') : t('Failed to modify datastream properties');
    $properties = $datastream_properties->getProperties();
    return json_encode(array('success' => TRUE, 'msg' => $message, 'data' => $properties));
  }
}

/**
 * Checks if an object has members.
 * 
 * @param string $pid 
 * 
 * @return boolean
 */
function content_model_viewer_object_has_members($pid) {
  module_load_include('inc', 'fedora_repository', 'CollectionClass');
  $collection = new CollectionClass();
  $results = $collection->getRelatedItems($pid);
  $results = trim($results);
  if ($results != '') {
    $document = new DOMDocument();
    $document->loadXML($results);
    $path = new DOMXPath($document);
    $path->registerNamespace('sparql', 'http://www.w3.org/2001/sw/DataAccess/rf1/result');
    $results = $path->query('//sparql:result');
    $count = $results->length;
    return $count > 0;
  }
  return FALSE;
}

/**
 *
 * @param string $pid 
 *   A Fedora Object PID.
 * @return boolean
 *   TRUE if there are settings defined for the given Content Model, FALSE otherwise.
 */
function content_model_viewer_model_has_settings($pid) {
  $query = db_query('SELECT count(pid) FROM content_model_viewer_models WHERE id > 1 AND pid = "%s"', $pid);
  return (db_result($query) > 0) ? TRUE : FALSE;
}

/**
 * Gets the custom settings for the given $pid.
 * 
 * If $model is not provided get the default settings.
 * 
 * @param string $model_id
 *   The model the settings are associated with.
 * 
 * @return array
 *   The rules associated with this fedora object.
 */
function content_model_viewer_get_settings($model_id = 1) {
  $settings = array();
  $query = db_query('SELECT * FROM content_model_viewer_datastream_rules WHERE model_id = "%d"', $model_id);
  while ($data = db_fetch_object($query)) {
    $item = array();
    foreach ($data as $key => $value) {
      $item[$key] = $value;
    }
    $settings[] = $item;
  }
  return $settings;
}

/**
 * Orders the settings for the given datastream, based on the MIME Type and DSID of the datastream. Also filter out 
 * settings that don't apply to this datastream.
 * 
 * If MIME type restricts, and DSID passes.
 * 
 * @param array $settings 
 * @param string $mime
 * @param string $dsid
 * 
 * @return array
 */
function content_model_viewer_order_settings(array $settings) {
  
}

/**
 * Gets the model id that is used to identitfy the custom settings for the given content model, identified by $pid.
 * 
 * @param string $pid 
 *   A fedora object pid.
 * 
 * @return int
 *   Returns the model_id  
 */
function content_model_viewer_get_model_id($pid) {
  return db_result(db_query('SELECT id FROM %s WHERE id > 1 AND pid = "%s"', CONTENT_MODEL_VIEWER_SETTINGS_TABLE, $pid));
}

/**
 * Checks to see if the user can view the given datastream of the given Fedora Object.
 * 
 * @param string $pid
 *   The Fedora Objects pid.
 * @param string $dsid 
 *   The Datastream ID.
 * 
 * @return boolean
 *   TRUE if the end user is permitted to view the datastream, FALSE otherwise.
 */
function content_model_viewer_is_viewing_permitted($pid, $dsid) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  module_load_include('inc', 'fedora_repository', 'ContentModel');
  $item = new Fedora_Item($pid);
  $content_model = ContentModel::loadFromObject($pid);
  $pid = $content_model->pid;
  $model_id = content_model_viewer_model_has_settings($pid) ? content_model_viewer_get_model_id($pid) : 1;
  $settings = content_model_viewer_get_settings($model_id);
  $permitted = TRUE; // Default TRUE.

  foreach ($settings as $setting) {
    if (($setting['mime'])) {
      
    }
  }
  return $permitted;
}

